config/routes.rb
Cloud1::Application.routes.draw do
  resources :dvd_actors

  resources :directors

  resources :actors

  resources :dvds

   root :to => 'dvds#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  validates_presence_of  :name
  validates_uniqueness_of :name
  validates_presence_of  :gender
  attr_accessible :dvd_actor, :dob, :gender, :name
  has_many :dvd_actor
  has_many :dvds, :through => :dvd_actor
  attr_accessor :dvd_actor
  after_save :update_dvds
  
  GENDER_TYPES = ["Mail", "Female", "Other"]

  private 
  def update_dvds
    dvds.delete_all
    selected_dvds = dvd_actor.nil? ? [] : dvd_actor.keys.collect{|id| 
    	puts "id = #{id}"
    		Dvd.find_by_id(id)}
    selected_dvds.each {|dvd| self.dvds << dvd}
  end

  
end

 
 

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
		get_all_dvds
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actors }
    end
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])
    #get_all_dvds
		get_all_dvds_for_actor
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/new
  # GET /actors/new.json
  def new
    @actor = Actor.new
		get_all_dvds
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
    get_all_dvds
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(params[:actor])
    get_all_dvds

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render json: @actor, status: :created, location: @actor }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.json
  def update
    @actor = Actor.find(params[:id])
		get_all_dvds
    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url }
      format.json { head :no_content }
    end
  end
  
  
  def get_all_dvds
    @dvds = Dvd.find(:all, :order => :name)
  end
  
    
  def get_all_dvds_for_actor
   # @ndvds = Dvd.find_by_name(:name)
        @dvds = Dvd.find(:all, :order => :name)

				
  end
  

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
   <b> <%= f.label :name %><br /> </b>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <b> <%= f.label 'Date Of Birth' %><br /> </b>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
   <b> <%= f.label  :gender %><br /> </b>
    <%= f.select :gender,options_for_select([ "Male", "Female" ], "Male") %>
  </div>
<div
  <div class="actions">
  
<b> DVD's <br> </b>

 <% @dvds.each do |dvd| %>
		<%= check_box_tag(
			"actor[dvd_actor][#{dvd.id}]", 
			"1", 
			@actor.dvds.detect{|d| d == dvd}) %>
			<%= "#{dvd.name}"%><br />
<% end %>

<br> 
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>
	
<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<h1>Listing actors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Dob</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @actors.each do |actor| %>
  <tr>
    <td><%= actor.name %></td>
    <td><%= actor.dob %></td>
    <td><%= actor.gender %></td>
    <td><%= link_to 'Show', actor %></td>
    <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
    <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @actor.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @actor.dob %>
</p>

<p>
  <b>Gender:</b>
  <%= @actor.gender %>
</p>

<% @dvds.each do |dvd| %>
			<%= check_box_tag(
				"actor[dvd_actor][#{dvd.id}]", 
				"1", 
				@actor.dvds.detect{|d| d == dvd}) %>
			<%= "#{dvd.name}"%><br />
<% end %>
<p>
<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>