config/routes.rb
Cloud1::Application.routes.draw do
  resources :dvd_actors

  resources :directors

  resources :actors

  resources :dvds

   root :to => 'dvds#index'

end

app/models/dvd_actor.rb
class DvdActor < ActiveRecord::Base
  attr_accessible :actor_id, :dvd_id
  belongs_to :dvd
  belongs_to :actor 
end

app/controllers/dvd_actors_controller.rb
class DvdActorsController < ApplicationController
  # GET /dvd_actors
  # GET /dvd_actors.json
  def index
    @dvd_actors = DvdActor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dvd_actors }
    end
  end

  # GET /dvd_actors/1
  # GET /dvd_actors/1.json
  def show
    @dvd_actor = DvdActor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dvd_actor }
    end
  end

  # GET /dvd_actors/new
  # GET /dvd_actors/new.json
  def new
    @dvd_actor = DvdActor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dvd_actor }
    end
  end

  # GET /dvd_actors/1/edit
  def edit
    @dvd_actor = DvdActor.find(params[:id])
  end

  # POST /dvd_actors
  # POST /dvd_actors.json
  def create
    @dvd_actor = DvdActor.new(params[:dvd_actor])

    respond_to do |format|
      if @dvd_actor.save
        format.html { redirect_to @dvd_actor, notice: 'Dvd actor was successfully created.' }
        format.json { render json: @dvd_actor, status: :created, location: @dvd_actor }
      else
        format.html { render action: "new" }
        format.json { render json: @dvd_actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dvd_actors/1
  # PUT /dvd_actors/1.json
  def update
    @dvd_actor = DvdActor.find(params[:id])

    respond_to do |format|
      if @dvd_actor.update_attributes(params[:dvd_actor])
        format.html { redirect_to @dvd_actor, notice: 'Dvd actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dvd_actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dvd_actors/1
  # DELETE /dvd_actors/1.json
  def destroy
    @dvd_actor = DvdActor.find(params[:id])
    @dvd_actor.destroy

    respond_to do |format|
      format.html { redirect_to dvd_actors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dvd_actors_helper.rb
module DvdActorsHelper
end

app/views/dvd_actors/_form.html.erb
<%= form_for(@dvd_actor) do |f| %>
  <% if @dvd_actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dvd_actor.errors.count, "error") %> prohibited this dvd_actor from being saved:</h2>

      <ul>
      <% @dvd_actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dvd_id %><br />
    <%= f.number_field :dvd_id %>
  </div>
  <div class="field">
    <%= f.label :actor_id %><br />
    <%= f.number_field :actor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dvd_actors/edit.html.erb
<h1>Editing dvd_actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @dvd_actor %> |
<%= link_to 'Back', dvd_actors_path %>

app/views/dvd_actors/index.html.erb
<h1>Listing dvd_actors</h1>

<table>
  <tr>
    <th>Dvd</th>
    <th>Actor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dvd_actors.each do |dvd_actor| %>
  <tr>
    <td><%= dvd_actor.dvd_id %></td>
    <td><%= dvd_actor.actor_id %></td>
    <td><%= link_to 'Show', dvd_actor %></td>
    <td><%= link_to 'Edit', edit_dvd_actor_path(dvd_actor) %></td>
    <td><%= link_to 'Destroy', dvd_actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dvd actor', new_dvd_actor_path %>

app/views/dvd_actors/new.html.erb
<h1>New dvd_actor</h1>

<%= render 'form' %>

<%= link_to 'Back', dvd_actors_path %>

app/views/dvd_actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dvd:</b>
  <%= @dvd_actor.dvd_id %>
</p>

<p>
  <b>Actor:</b>
  <%= @dvd_actor.actor_id %>
</p>


<%= link_to 'Edit', edit_dvd_actor_path(@dvd_actor) %> |
<%= link_to 'Back', dvd_actors_path %>