config/routes.rb
Cloud1::Application.routes.draw do
  resources :dvd_actors

  resources :directors

  resources :actors

  resources :dvds

   root :to => 'dvds#index'

end

app/models/dvd.rb
class Dvd < ActiveRecord::Base
  validates_presence_of  :name
  validates_uniqueness_of :name
  attr_accessible :asin, :date, :name, :summary, :dvd_actor, :director_id
  has_many :dvd_actor
  has_many :actors, :through => :dvd_actor
  has_one  :director
  attr_accessor :dvd_actor
  
  after_save :update_actors
  
  def asinurl
  #Should we move this out to yaml or some other external config file?
   "http://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Dmovies-tv&field-keywords=#{self.asin}"
  end
  private 
  def update_actors
    actors.delete_all
    selected_actors = dvd_actor.nil? ? [] : dvd_actor.keys.collect{|id| Actor.find_by_id(id)}
    selected_actors.each {|actor| self.actors << actor}
    
  end
end

app/controllers/dvds_controller.rb
class DvdsController < ApplicationController
  # GET /dvds
  # GET /dvds.json
  def index
    @dvds = Dvd.all
    get_all_actors

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dvds }
    end
  end

  # GET /dvds/1
  # GET /dvds/1.json
  def show
    @dvd = Dvd.find(params[:id])
    get_all_actors
    get_director

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dvd }
    end
  end

  # GET /dvds/new
  # GET /dvds/new.json
  def new
    @dvd = Dvd.new
    get_all_actors

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dvd }
    end
  end

  # GET /dvds/1/edit
  def edit
    @dvd = Dvd.find(params[:id])
    get_all_actors
    get_director
  end

  # POST /dvds
  # POST /dvds.json
  def create
    @dvd = Dvd.new(params[:dvd])
		get_all_actors
    respond_to do |format|
      if @dvd.save
        format.html { redirect_to @dvd, notice: 'Dvd was successfully created.' }
        format.json { render json: @dvd, status: :created, location: @dvd }
      else
        format.html { render action: "new" }
        format.json { render json: @dvd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dvds/1
  # PUT /dvds/1.json
  def update
    @dvd = Dvd.find(params[:id])
    get_all_actors
    get_director

    respond_to do |format|
      if @dvd.update_attributes(params[:dvd])
        format.html { redirect_to @dvd, notice: 'Dvd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dvd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dvds/1
  # DELETE /dvds/1.json
  def destroy
    @dvd = Dvd.find(params[:id])
    @dvd.destroy

    respond_to do |format|
      format.html { redirect_to dvds_url }
      format.json { head :no_content }
    end
  end

  def get_all_actors
    @actors = Actor.find(:all, :order => :name)
  end


  def get_director
  	 tdvd = Dvd.find(params[:id])
  	 director_id = tdvd.director_id
  	 dname = Director.find(director_id)
  	 @thedirector = dname.name
  end
  
end

app/helpers/dvds_helper.rb
module DvdsHelper
end

app/views/dvds/_form.html.erb
<%= form_for(@dvd) do |f| %>
  <% if @dvd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dvd.errors.count, "error") %> prohibited this dvd from being saved:</h2>

      <ul>
      <% @dvd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <b> <%= f.label :name %><br /> </b>
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <b> <%= f.label :date %><br /> </b>
    <%= f.date_select :date %>
  </div>
  <div class="field">
  <b> <%= f.label :summary %><br /> </b>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
  <b> <%= f.label :asin %><br /> </b>
    <%= f.text_field :asin %>
  </div>
<div class="field">
  <b> <%= f.label :actors %><br /> </b>
    
<% @actors.each do |actor| %>
			<%= check_box_tag(
                            "dvd[dvd_actor][#{actor.id}]", 
                            "1", 
                            @dvd.actors.detect{|d| d == actor}) %>
			<%= "#{actor.name}"%><br/>
		<% end %>
</div>

<p>
  <b> Current Director:</b> <br>
  <%= @thedirector %>
</p>

<div class="field">
    <b> <%= f.label :director, "Director List" %><br/> </b>
    <%= f.select :director_id, options_from_collection_for_select(Director.all, :id, :name) %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dvds/edit.html.erb
<h1>Editing dvd</h1>

<%= render 'form' %>

<%= link_to 'Show', @dvd %> |
<%= link_to 'Back', dvds_path %>

app/views/dvds/index.html.erb
<h1>Listing dvds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Summary</th>
    <th>Asin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dvds.each do |dvd| %>
  <tr>
    <td><%= dvd.name %></td>
    <td><%= dvd.date %></td>
    <td><%= dvd.summary %></td>
    <td><%= link_to dvd.asin, dvd.asinurl %></td>
    <td><%= link_to 'Show', dvd %></td>
    <td><%= link_to 'Edit', edit_dvd_path(dvd) %></td>
    <td><%= link_to 'Destroy', dvd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dvd', new_dvd_path %>

app/views/dvds/new.html.erb
<h1>New dvd</h1>

<%= render 'form' %>

<%= link_to 'Back', dvds_path %>

app/views/dvds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dvd.name %>
</p>

<p>
  <b>Date:</b>
  <%= @dvd.date %>
</p>

<p>
  <b>Summary:</b>
  <%= @dvd.summary %>
</p>

<p>
  <b>Asin:</b>
  <%= @dvd.asin %>
</p>

<p>
  <b>Director:</b>
  <%= @thedirector %>
</p>

<% @actors.each do |actor| %>
			<%= check_box_tag(
				"dvd[dvd_actor][#{actor.id}]", 
				"1", 
				@dvd.actors.detect{|d| d == actor}) %>
				<%= "#{actor.name}"%><br />
<% end %>
		
</div>


<%= link_to 'Edit', edit_dvd_path(@dvd) %> |
<%= link_to 'Back', dvds_path %>